### ISSUE TITLE
idEleve

### ISSUE THREAD

**Issue by BugBoys100** [maelgangloff/kdecole-api#257]
It's not really a bug but in almost all functions, they take idEleve as a parameter, but I can't find it anywhere, either on my ent side or in a variable that we create with `new Kdecole(TOKEN)`
Can you help me please?

**Comment by maelgangloff** [comment]
Hello,
this identifier is only used to select the data of a single student, it is useful if you are a parent of more than one child for example.
If you are a parent, you can find idEleve with the getInfoUtilisateur() method.
If you are a student, it is not necessary to fill in this identifier because the data concerns you. You can just ignore this parameter.
